### ISSUE TITLE
Using without POS

### ISSUE THREAD

**Issue by hwahyeon** [kpech21/Greek-Stemmer#6]
Hello, @kpech21
Is there a way to use this package without POS (second parameter)? If not, are you thinking of expanding it?

Thank you
hwahyeon

**Comment by kpech21** [comment]
Hi @hwahyeon,

Sorry for my late response.

Unfortunately, it is not feasible to exclude POS. The stemming rules are based on the POS in order to have the best performance.

On the other hand, in terms of your first question, it is feasible to support more programming languages (like JavaScript), but we should make changes in the architecture of the library. To date, we can use the library utilizing the relevant Python pip or the source code.

Thanks,
Konstantinos

**Comment by hwahyeon** [comment]
Hi @kpech21 
Thank you for your reply! I am working on different things right now, but I would love to come back and work on this later (convert yours to javascript)

Thanks,
hwahyeon
